### ISSUE TITLE
[Feedback] Nice concept! Couple QOL ideas.

### ISSUE THREAD

**Issue by murphatron** [sandaru1/laravel-eloquent-model-attributes#1]
It's funny that you just published this today and I was looking for something close to this. I like where you're going with this! I wanted to offer a couple quality of life ideas. 

1. I think it would be really great to have the extension automatically generate class (model) level PHPDocs with [`@property` ](https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.property.pkg.html) attributes so each of the columns can be validated with intellisense. This shouldn't be too difficult to work into your extension since you're already handling columns and their casting types. This is something I manually do now but it is tedious.

    - In addition to columns in PHPDocs, is relations. This is more advanced but could be helpful for developers to streamline access to their models . `@property-read` is a good PHPDoc choice for these.
   
3. Perhaps expose ignored fillable columns to configuration as an array of patterns.

**Comment by sandaru1** [comment]
Thanks for the feedback.

1. The PHPDocs is a great idea. I'll look into it.
2. Configurations are in the works. It will be available soon.

**Comment by sandaru1** [comment]
The configuration options are available in the new version now.

**Comment by ctf0** [comment]
a couple of things as well,
1. is this the correct description ? https://github.com/sandaru1/laravel-eloquent-model-attributes/blob/062152e7c8cc79172de3b37fb3971dd6b9f59439/package.json#L109

2. get the plural table name from the current file class name (get it with either php-parser or file symbols) if nothing is added to the input box.

**Comment by sandaru1** [comment]
1. Thanks, I somehow missed it. I'll add a fix.
2. It's already being done in version 0.0.4

**Comment by sandaru1** [comment]
PHPDoc is option is added. You can use the command : "Insert PHPDoc for Eloquent Model Attributes".
