### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YafaKh** [sandaru1/laravel-eloquent-model-attributes#2]
An error occured while trying to parse the .env file. ENOENT: no such file or directory, open '/c:/xampp/htdocs/portal1/.env'

**Comment by sandaru1** [comment]
Windows seems to be adding an extra "/" to the path. I'm looking into it.

**Comment by SantanuDatta** [comment]
facing the same issue

**Comment by SherifShabana** [comment]
Same issue as well.

**Comment by nsubramkavin** [comment]
same issue as well

**Comment by wahhabc23** [comment]
same issue

**Comment by wahhabc23** [comment]
> An error occured while trying to parse the .env file. ENOENT: no such file or directory, open '/c:/xampp/htdocs/portal1/.env'

I have fixed this issue in windows, and I have shared a pull request or you guyz can download vsix file from here [https://github.com/wahhabc23/laravel-eloquent-model-attributes](url)

**Comment by SantanuDatta** [comment]
> > An error occured while trying to parse the .env file. ENOENT: no such file or directory, open '/c:/xampp/htdocs/portal1/.env'
> 
> I have fixed this issue in windows, and I have shared a pull request or you guyz can download vsix file from here [https://github.com/wahhabc23/laravel-eloquent-model-attributes](url)

Thanks for that but since this plugin hasn't been maintained for sometime now I think someone should take over and maintain or add new features to it as well, it has potential

**Comment by sandaru1** [comment]
> > An error occured while trying to parse the .env file. ENOENT: no such file or directory, open '/c:/xampp/htdocs/portal1/.env'
> 
> I have fixed this issue in windows, and I have shared a pull request or you guyz can download vsix file from here [https://github.com/wahhabc23/laravel-eloquent-model-attributes](url)

Thanks. I published the new extension and added you as a contributors to the README.
